"""Node to run analysis of oligonucleotide simulations"""

from pathlib import Path
from typing import Any
import pytest
from maize.core.node import Node
from maize.utilities.io import Config
from maize.core.interface import Input, Parameter, FileParameter
from maize.utilities.testing import TestRig
from maize.steps.mai.gromacs_rna.file_utils_analysis import (
    average_interactions,
    compute_rmsf,
    contacts_with_ions,
    remove_redundancy,
    group_finder,
)


class OligoAnalysis(Node):
    """
    Analyzes Gromacs-run oligonucleotide simulations
    and extracts features in the form of a csv file.

    Notes
    -----
    - Requires a maize environment with ``prolif`` tool installed.
    For detailed documentation, follow <https://prolif.readthedocs.io/en/stable/>_.
    The github repo for this tool can be found in
    `ProLIF <https://github.com/chemosim-lab/ProLIF/>`_.
    To install use::
    conda install -c conda-forge prolif

    -- Requires Gromacs. This can be loaded as a module in the config file

    -- Requires x3dna-dssr. This tool can also be loaded as a module in the config file.
    Follow the official page <https://x3dna.org>_ for more information.
    """

    required_callables = ["gmx", "x3dna-dssr"]

    # Inputs

    inp_data_path: Input[Path] = Input()
    """Path to input files to access trajectories and topologies generated by MD simulations"""

    inp_csv: FileParameter[Path] = FileParameter()
    """Path to input csv file containing list of sequences and chemical modifications"""

    dest_path: Input[Path] = Input()
    """Path to destination to save the output csv file containing features from simulations"""

    # Options

    molecules: Parameter[int] = Parameter(default=1)
    """Number of molecules/systems to analyse"""

    replicas: Parameter[int] = Parameter(default=1)
    """Number of replicas per system"""

    skip_frames: Parameter[int] = Parameter(default=1)
    """Number of frames to skip in the trajectory for analysis"""

    skip_frames_pdb: Parameter[int] = Parameter(default=1)
    """Number of frames to skip in the trajectory 
    to generate concatenated pdb file for x3dna analysis"""

    num_jobs: Parameter[int | None] = Parameter(default=1)
    """Number of processes to run ProLIF fingerprint analysis in parallel"""

    cutoff_interface: Parameter[int | float] = Parameter(default=10)
    """Cutoff distance (Ångström) to select atoms in the vicinity of a molecule 
    in order to define an interface -- ProLIF analysis"""

    cutoff_ions: Parameter[int | float] = Parameter(default=4.5)
    """Cutoff distance (Ångström) to count the number of ions surrounding the oligo"""

    def run(self) -> None:
        import prolif as plf
        import MDAnalysis as mda
        import pandas as pd
        import numpy as np
        import json

        data_path = self.inp_data_path.receive()
        dataset_path = self.inp_csv.filepath
        dest = self.dest_path.receive()
        nsys = self.molecules.value
        nreps = self.replicas.value
        skip_n = self.skip_frames.value
        skip_3dna = self.skip_frames_pdb.value
        njobs = self.num_jobs.value
        cutoff_int = self.cutoff_interface.value
        cutoff_na = self.cutoff_ions.value

        # Read the sequence dataset
        dataset = pd.read_csv(dataset_path)

        dict_inter_rna = {}

        # List of Prolif interactions to analyze
        interactions = [
            "Anionic",
            "CationPi",
            "Cationic",
            "EdgeToFace",
            "FaceToFace",
            "HBAcceptor",
            "HBDonor",
            "Hydrophobic",
            "PiCation",
            "PiStacking",
            "VdWContact",
            "XBAcceptor",
            "XBDonor",
        ]

        # Labels for interactions within guide strand and target strand
        int_labels_guide = ["Guide_" + string for string in interactions]
        int_labels_target = ["Target_" + string for string in interactions]

        # Combine all Prolif interaction types
        int_labels_all = interactions + int_labels_guide + int_labels_target

        dict_interactions_all: dict[str, list[float]] = {key: [] for key in int_labels_all}

        # List of x3dna interaction labels
        x3dna_labels = [
            "base_pairs",
            "WC_pairs",
            "atom2base_caps",
            "helical_rise",
            "helical_radius",
            "minor_groove_width",
            "major_groove_width",
        ]

        dict_interactions_x3dna: dict[str, list[Any]] = {key: [] for key in x3dna_labels}

        rna_list = dataset["gseq_base"]

        # Looping over the number of systems/molecules
        for sys in range(1, nsys + 1):

            system = Path(f"{data_path}/mol{sys}")

            ndx = system / Path("index.ndx")
            gro = system / Path(f"replica1/Prod/mol{sys}_replica1_Prod_confout.gro")

            # Getting length of RNA in each system
            len_rna = len(rna_list[sys - 1])

            traj_list = []

            # Create index group for 1 strand to run trjconv.
            # To center the molecule in the box, you need index of strand 1 (guide strand)
            command_makendx = (
                f"{self.runnable['gmx']} make_ndx "
                f"-f {gro.as_posix()} "
                f"-n {ndx.as_posix()} "
                f"-o {ndx.as_posix()} "
            )
            run_makendx = self.run_command(
                command_makendx, command_input=f"ri 1-{len_rna} \nq\n", raise_on_failure=False
            )
            if run_makendx.returncode != 0:
                continue

            # Looping over the number of simulation replicates
            for rep in range(1, nreps + 1):
                rep_path = system / Path(f"replica{rep}/Prod/")

                # Get paths of files necessary to run analysis commands
                gro = rep_path / Path(f"mol{sys}_replica{rep}_Prod_confout.gro")
                xtc = rep_path / Path(f"mol{sys}_replica{rep}_Prod_traj.xtc")
                xtcout = rep_path / Path(f"mol{sys}_replica{rep}_skipped.xtc")
                tpr = rep_path / Path(f"mol{sys}_replica{rep}_Prod_topol.tpr")

                # Run gmx trjconv to center the molecule in the box and remove pbc
                # You can choose to skip "skip_n" number of frames in the trajectory
                command_trjconv = (
                    f"{self.runnable['gmx']} trjconv "
                    f"-f {xtc.as_posix()} "
                    f"-s {tpr.as_posix()} "
                    f"-n {ndx.as_posix()} "
                    f"-o {xtcout.as_posix()} "
                    f"-skip {skip_n}"
                    f" -center -pbc mol "
                )

                # Get index groups for strand 1 (guide strand) of the duplex
                ndx_str = group_finder(ndx, f"r_1-{len_rna}")
                run_trjconv = self.run_command(
                    command_trjconv, command_input=f"{ndx_str} 0\n", raise_on_failure=False
                )
                if run_trjconv.returncode != 0:
                    continue
                self.logger.info("Generated skipped trajectories %s", xtcout.absolute())

                # Delete gmx backup files
                gmx_backup_files = rep_path.glob("#*")
                for file in gmx_backup_files:
                    file.unlink()

                traj_list.append(
                    f"{xtcout}"
                )  # Concatenating paths to simulation replicas for input to mdanalysis

            # Delete gmx backup files
            gmx_backup_files = system.glob("#*")
            for file in gmx_backup_files:
                file.unlink()

            # Join the paths of the simulation replicas to serve as input for gmx trjcat.
            # Needed for x3dna analysis
            all_trajs = " ".join(traj_list)  # Input for gmx trjcat needed for x3dna analysis

            # Load topology and replicate trajectories for each complex
            # to create an MDanalysis universe
            u = mda.Universe(tpr, traj_list)

            # RNA-RNA interactions

            rna_atoms = u.select_atoms(f"resid 1-{len_rna*2}")  # Select whole duplex

            rna_guide = u.select_atoms(f"resid 1-{len_rna}")  # Select strand 1
            rna_target = u.select_atoms(f"resid {len_rna+1}-{len_rna*2}")  # Select strand 2

            # Select atoms at the interface in guide strand
            rna_guide_int = u.select_atoms(
                f"resid 1-{len_rna} and byres around {cutoff_int} (resid {len_rna+1}-{len_rna*2})"
            )
            # Select atoms at the interface in target strand
            rna_target_int = u.select_atoms(
                f"(resid {len_rna+1}-{len_rna*2}) and byres around {cutoff_int} resid 1-{len_rna}"
            )

            # Select sodium atoms
            ions = u.select_atoms("name NA")

            # Get ProLIF-based interaction fingerprints

            # Interactions between guide and target

            fp_inter_rna = plf.Fingerprint(interactions, count=True)
            fp_inter_rna.run(u.trajectory, rna_guide_int, rna_target_int, n_jobs=njobs)

            df_inter_rna = fp_inter_rna.to_dataframe()
            # Obtain averaged values over trajectories
            dict_inter_rna = average_interactions(df_inter_rna)

            # Interactions within guide strand
            fp_intra_guide = plf.Fingerprint(interactions, count=True)
            fp_intra_guide.run(u.trajectory, rna_guide, rna_guide, n_jobs=njobs)

            df_intra_guide = fp_intra_guide.to_dataframe()
            dict_intra_guide = average_interactions(df_intra_guide)

            # Interactions within target strand

            fp_intra_target = plf.Fingerprint(interactions, count=True)
            fp_intra_target.run(u.trajectory, rna_target, rna_target, n_jobs=njobs)

            df_intra_target = fp_intra_target.to_dataframe()
            dict_intra_target = average_interactions(df_intra_target)

            # Appending interactions for every system to a dictionary
            for key in int_labels_all:
                if key in dict_inter_rna:
                    dict_interactions_all[key].append(dict_inter_rna[key])
                elif key[6:] in dict_intra_guide:  # Prefix  : Guide_{key}
                    dict_interactions_all[key].append(dict_intra_guide[key[6:]])
                elif key[7:] in dict_intra_target:  # Prefix  : Target_{key}
                    dict_interactions_all[key].append(dict_intra_target[key[7:]])
                elif key[6:] not in dict_intra_guide and key in int_labels_guide:
                    dict_interactions_all[key].append(0)
                elif key[7:] not in dict_intra_target and key in int_labels_target:
                    dict_interactions_all[key].append(0)
                else:
                    dict_interactions_all[key].append(0)

            self.logger.info("ProLIF analysis complete for system %s", sys)

            # RMSF of RNA using MDAnalysis
            rmsf_rna = compute_rmsf(u, len_rna)

            if "rmsf_rna" in dict_interactions_all.keys():
                dict_interactions_all["rmsf_rna"].append(rmsf_rna)
            else:
                dict_interactions_all["rmsf_rna"] = [rmsf_rna]

            self.logger.info("RMSF calculation complete for system %s", sys)

            # Interactions of RNA with ions
            ca = contacts_with_ions(u, rna_atoms, ions, cutoff_na)

            if "ion_contacts" in dict_interactions_all.keys():
                dict_interactions_all["ion_contacts"].append(ca)
            else:
                dict_interactions_all["ion_contacts"] = [ca]

            self.logger.info("Ion contacts analysis complete for system %s", sys)

            # SASA

            # Get index group for the RNA duplex
            ndx_rna = group_finder(ndx, "RNA")

            # Concatenate replicate trajectories
            concat_xtc = Path(f"{system}/concat.xtc")
            command_trjcat = (
                f"{self.runnable['gmx']} trjcat "
                f"-f {all_trajs} "
                f"-o {concat_xtc.as_posix()} "
                f" -cat "
            )
            run_trjcat = self.run_command(command_trjcat, raise_on_failure=False)
            if run_trjcat.returncode != 0:
                continue
            self.logger.info(
                "Concatenated replicate trajectories for x3dna analysis%s", concat_xtc.absolute()
            )

            # Run gmx sasa calculation
            sasa_out = Path(f"{system}/sasa.xvg")
            command_sasa = (
                f"{self.runnable['gmx']} sasa "
                f"-f {concat_xtc.as_posix()} "
                f"-s {tpr} "
                f"-n {ndx} "
                f"-o {sasa_out}"
            )
            run_sasa = self.run_command(
                command_sasa, command_input=f"{ndx_rna}\n", raise_on_failure=False
            )
            if run_sasa.returncode != 0:
                continue

            sasa = []
            with open(f"{sasa_out}", "r", encoding="utf-8") as fp:
                for line in fp:
                    if not line.startswith("#") and not line.startswith("@"):
                        sasa.append(float(line.split()[1]))

            if "sasa" in dict_interactions_all.keys():
                dict_interactions_all["sasa"].append(float(np.mean(sasa)))
            else:
                dict_interactions_all["sasa"] = [float(np.mean(sasa))]

            # X3dna analysis

            pdb_out = Path(f"{system}/concat.pdb")
            # Running gmx trjconv to generate pdb file for the concatenated trajectory
            command_trjconv2 = (
                f"{self.runnable['gmx']} trjconv "
                f"-f {concat_xtc.as_posix()} "
                f"-s {tpr.as_posix()} "
                f"-n {ndx.as_posix()} "
                f"-o {pdb_out.as_posix()} "
                f"-skip {skip_3dna}"
            )
            run_trjconv2 = self.run_command(
                command_trjconv2, command_input=f"{ndx_rna}\n", raise_on_failure=False
            )
            if run_trjconv2.returncode != 0:
                continue
            self.logger.info(
                "PDB generated from concatenated trajectories for x3dna analysis%s",
                pdb_out.absolute(),
            )

            # Running x3dna analysis tool on the concatenated pdb
            x3dna_out = Path(f"{system}/3dna.json")
            command_x3dna = (
                f"{self.runnable['x3dna-dssr']}"
                f" -i={pdb_out.as_posix()} "
                f" -o={x3dna_out.as_posix()} "
                f" --json --nmr --more"
            )
            run_x3dna = self.run_command(command_x3dna, raise_on_failure=False)
            if run_x3dna.returncode != 0:
                continue
            self.logger.info(
                "JSON file generated from x3dna run%s",
                x3dna_out.absolute(),
            )

            # Reading x3dna output json file
            file_json = open(f"{x3dna_out}", encoding="utf-8")
            x3dna_json = json.load(file_json)

            bp_count_list = []
            wc_count_list = []
            cap_count_list = []
            hrise_list = []
            hradius_list = []
            min_gr_list = []
            maj_gr_list = []

            # Looping over the models in the json file,
            # where each model is a time point in the trajectory
            for model in x3dna_json["models"]:

                # Number of base pairs in duplex
                bp_count = 0
                wc_count = 0
                if "pairs" in model["parameters"]:
                    for pair in model["parameters"]["pairs"]:
                        if (
                            pair["nt1"].startswith(f"{model['model']}:A.") is True
                            and pair["nt2"].startswith(f"{model['model']}:B.") is True
                        ):
                            bp_count += 1
                            if pair["name"] == "WC":
                                wc_count += 1

                # Number of atom 2 base caps between 2 strands
                cap = 0
                if "atom2bases" in model["parameters"]:
                    for pair in model["parameters"]["atom2bases"]:
                        if (
                            f"@{model['model']}:A." in pair["atom"]
                            and f"{model['model']}:B." in pair["nt"]
                        ):
                            cap += 1
                        if (
                            f"@{model['model']}:B." in pair["atom"]
                            and f"{model['model']}:A." in pair["nt"]
                        ):
                            cap += 1

                # Helical parameters of duplex
                num_helices = model["parameters"]["num_helices"]
                if num_helices == 1 and (
                    model["parameters"]["helices"][0]["num_pairs"] >= (0.7 * len_rna)
                ):  # Calculate helical parameters if the length is more than 7/10 of RNA length

                    # Helical rise and helical radius
                    helical_rise = model["parameters"]["helices"][0]["helical_rise"]
                    helical_radius = model["parameters"]["helices"][0]["helical_radius"]

                    # Minor and major groove widths
                    for pair in model["parameters"]["helices"][0]["pairs"]:
                        if "groove_widths" in pair.keys():
                            if pair["groove_widths"][1] is not None:
                                min_gr_list.append(pair["groove_widths"][1])
                            if pair["groove_widths"][3] is not None:
                                maj_gr_list.append(pair["groove_widths"][3])

                else:
                    helical_rise = np.nan
                    helical_radius = np.nan
                    min_gr_list.append(np.nan)
                    maj_gr_list.append(np.nan)

                num_helices = model["parameters"]["num_helices"]
                if num_helices == 1 and (
                    model["parameters"]["helices"][0]["num_pairs"] >= (0.7 * len_rna)
                ):
                    for pair in model["parameters"]["helices"][0]["pairs"]:
                        if "groove_widths" in pair.keys():
                            if pair["groove_widths"][1] is not None:
                                min_gr_list.append(pair["groove_widths"][1])
                            if pair["groove_widths"][3] is not None:
                                maj_gr_list.append(pair["groove_widths"][3])

                bp_count_list.append(bp_count)
                wc_count_list.append(wc_count)
                cap_count_list.append(cap)
                hrise_list.append(helical_rise)
                hradius_list.append(helical_radius)

            # Appending averaged values into a dictionary for each interaction type
            dict_interactions_x3dna["base_pairs"].append(np.mean(bp_count_list))
            dict_interactions_x3dna["WC_pairs"].append(np.mean(wc_count_list))
            dict_interactions_x3dna["atom2base_caps"].append(np.mean(cap_count_list))
            dict_interactions_x3dna["helical_rise"].append(np.nanmean(hrise_list))
            dict_interactions_x3dna["helical_radius"].append(np.nanmean(hradius_list))
            dict_interactions_x3dna["minor_groove_width"].append(np.nanmean(min_gr_list))
            dict_interactions_x3dna["major_groove_width"].append(np.nanmean(maj_gr_list))

            self.logger.info("X3dna analysis complete for system %s", sys)

            # Removing temporary files
            temp_files = [
                Path.joinpath(system, "concat.xtc"),
                Path.joinpath(system, "concat.pdb"),
            ]
            for temp in temp_files:
                temp.unlink()  # Remove concatenated trajectory and pdb files after analysis

        dict_interactions_all = dict_interactions_all | dict_interactions_x3dna
        # Convert dictionary to dataframe
        df_interactions = pd.DataFrame.from_dict(dict_interactions_all)
        final_df = remove_redundancy(df_interactions)

        # Write final results to a csv file
        final_df.to_csv(f"{dest}/Oligo_Features.csv")


@pytest.fixture
def inp_data_path(shared_datadir: Path) -> Path:
    return shared_datadir / "md_output"


@pytest.fixture
def inp_csv(shared_datadir: Path) -> Path:
    return shared_datadir / "sequence_data.csv"


@pytest.fixture
def dest_path(shared_datadir: Path) -> Path:
    return shared_datadir


class TestSuiteAnalysis:
    def test_analysis(
        self, inp_data_path: Path, inp_csv: Path, dest_path: Path, test_config: Config
    ) -> None:

        rig = TestRig(OligoAnalysis, config=test_config)

        rig.setup_run(
            inputs={"inp_data_path": inp_data_path, "dest_path": dest_path},
            parameters={
                "inp_csv": inp_csv,
                "molecules": 2,
                "replicas": 1,
                "skip_frames": 1,
                "skip_frames_pdb": 1,
                "num_jobs": 1,
                "cutoff_interface": 10,
                "cutoff_ions": 4.5,
            },
        )

        output = dest_path / "Oligo_Features.csv"

        assert output is not None
        assert output.stat().st_size > 0.0
