"""Node to save output files generated by Gromacs runs"""

from pathlib import Path
import string
import shutil
import os
import re
from typing import Any, Optional, Generic, TypeVar, Dict, Tuple
from rdkit import Chem
from maize.core.node import Node, LoopedNode
from maize.core.interface import (
    Input,
    FileParameter,
    Flag,
)


T = TypeVar("T")


class SaveFile(Node, Generic[T]):
    """
    SaveFile class is a Node that receives a dictionary of files and saves them
    to specified locations within a destination folder. The dictionary keys are of type str and the values are either list[Path] or Path objects.
    """

    inp: Input[dict[str, Any]] = Input(mode="copy")
    """Dictionary of files input (keys are str, values are either Path or list[Path] objects)."""

    destination: FileParameter[Path] = FileParameter(exist_required=False)
    """The destination folder where files will be saved."""

    overwrite: Flag = Flag(default=False)
    """If True, will overwrite any previously existing file in the destination."""

    def run(self) -> None:
        files = self.inp.receive()
        self.logger.info("Files received %s", files)

        dest = self.destination.filepath
        self.logger.info("Parent destination is %s", dest)

        if not dest.is_dir():
            raise ValueError(f"Destination '{dest}' must be a directory")

        # Converting dictionary items to lists
        for key, value in files.items():
            if not isinstance(value, list):
                files[key] = [value]

        files = {k: [file.absolute() for file in file_list] for k, file_list in files.items()}
        for k, file_list in files.items():
            for file in file_list:
                rna_name = k
                dest_path = dest.absolute() / rna_name / file.name
                if not dest_path.exists():
                    dest_path.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(file, dest_path)
