
[autodockgpu]
python = "/home/${USER}/miniconda3/envs/maize-meeko/bin/python"
modules = ["CUDA", "GCC"]
commands.autodock_gpu = "/projects/mai/users/${USER}_thomas/src/AutoDock-GPU/bin/autodock_gpu_64wi" 

[gypsum]
scripts.gypsum.interpreter = "/home/${USER}/miniconda3/envs/gypsum/bin/python"
scripts.gypsum.location = "/projects/mai/users/${USER}_thomas/src/gypsum_dl/run_gypsum_dl.py"
